export const REQUEST_API_LIST_TO_DO = 'REQUEST_API_LIST_TO_DO';
export const RECEIVE_API_LIST_TO_DO = 'RECEIVE_API_LIST_TO_DO';
export const REQUEST_ADD_ITEM = 'REQUEST_ADD_ITEM';
export const REQUEST_DELETE_ITEM = 'REQUEST_DELETE_ITEM';
export const REQUEST_EDIT_ITEM = 'REQUEST_EDIT_ITEM';